Use feature flags more consistently to drop unnecessary dependancies and systems
Weasy666/bevy_svg pull request #31
Opened 2023-05-04 14:33 UTC by NiseVoid

Some changes to better respect the feature flags, as well as better support for having neither 2d nor 3d enabled, which makes the plugin just provide assets and requires the user to render the svgs theirselves. This change fixes an issue where bevy_sprite can be disabled but even if the 2d feature is disabled this crate fails to compile.

I'm not too happy about how the changes affect readability, so if you have any ideas on how this could be better structured please let me know.

2023-05-06 15:07 UTC, Weasy666 requested changes
Thanks for this contribution. 🙂
I think readability did not get that much worse. I think we could maybe improve it a bit, if we move the type aliases, `WithMesh`, `ChangedMesh` and `SvgMeshComponents` into the respective `...::svg2d::mod.rs`.
But i am not really sure if this actually would make it any better. 😅

2023-05-06 17:08 UTC, NiseVoid commented
> Thanks for this contribution. slightly_smiling_face I think readability did not get that much worse. I think we could maybe improve it a bit, if we move the type aliases, `WithMesh`, `ChangedMesh` and `SvgMeshComponents` into the respective `...::svg2d::mod.rs`. But i am not really sure if this actually would make it any better. sweat_smile

I'm not sure how the svg2d and svg3d files would work here, since there are three cases here: 2d enabled, 3d enabled, both enabled (which seems to be broken currently because both renderers add a MaterialPlugin which in turn add a ExtractComponent plugin for Handle<Svg>)

2023-05-07 17:13 UTC, Weasy666 commented
Oh...damn. Looks like that broke when i removed the custom pipelines, but doesn't matter for this PR.

The PR looks good to me. Thanks again!

2023-05-07 17:13 UTC, Weasy666 approved these changes

2023-05-07 17:13 UTC, merged